version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres-example-auth
    ports:
      - "5432:5432"
    env_file:
      - ./db/.env
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  database_data:
    driver: local