services:
  mb1:
    image: broadcaster:latest
    environment:
      DC: "/etc/dragonboat.yaml"
    restart: on-failure
    ports:
      - "9001:9090"
    volumes:
      - ./config/config-1.yaml:/etc/dragonboat.yaml
      - ./data/data-1:/data
    depends_on:
      - clickhouse-mb1
    networks:
      - appnet
    command: [ "./broadcaster"]
  mb2:
    image: broadcaster:latest
    restart: on-failure
    environment:
      DC: "/etc/dragonboat.yaml"
    ports:
      - "9002:9090"
    volumes:
      - ./config/config-2.yaml:/etc/dragonboat.yaml
      - ./data/data-2:/data
    depends_on:
      - clickhouse-mb2
    networks:
      - appnet
    command: [ "./broadcaster"]
  mb3:
    image: broadcaster:latest
    environment:
      DC: "/etc/dragonboat.yaml"
    restart: on-failure
    ports:
      - "9003:9090"
    volumes:
      - ./config/config-3.yaml:/etc/dragonboat.yaml
      - ./data/data-3:/data
    depends_on:
      - clickhouse-mb3
    networks:
      - appnet
    command: [ "./broadcaster"]
  clickhouse-mb1:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-mb1
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: default
    ports:
      - "8801:8123"
      - "9901:9000"
    volumes:
      - ./data/clickhouse_data_mb1:/var/lib/clickhouse
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - appnet

  clickhouse-mb2:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-mb2
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: default
    ports:
      - "8802:8123"
      - "9902:9000"
    volumes:
      - ./data/clickhouse_data_mb2:/var/lib/clickhouse
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - appnet

  clickhouse-mb3:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-mb3
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: default
    ports:
      - "8803:8123"
      - "9903:9000"
    volumes:
      - ./data/clickhouse_data_mb3:/var/lib/clickhouse
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - appnet

volumes:
  config:
    driver: local

networks:
  appnet: