services:
  broadcaster1:
    image: broadcaster:latest
    environment:
      DC: "/etc/dragonboat.yaml"
    restart: on-failure
    ports:
      - "9001:9090"
    command: ["./broadcaster"]
    volumes:
      - ./config/config-1.yaml:/etc/dragonboat.yaml
      - ./data/data-1:/data

  broadcaster2:
    image: broadcaster:latest
    restart: on-failure
    environment:
      DC: "/etc/dragonboat.yaml"
    ports:
      - "9002:9090"
    command: ["./broadcaster"]
    volumes:
      - ./config/config-2.yaml:/etc/dragonboat.yaml
      - ./data/data-2:/data

  broadcaster3:
    image: broadcaster:latest
    environment:
      DC: "/etc/dragonboat.yaml"
    restart: on-failure
    ports:
      - "9003:9090"
    command: ["./broadcaster"]
    volumes:
      - ./config/config-3.yaml:/etc/dragonboat.yaml
      - ./data/data-3:/data


volumes:
  config:
    driver: local
