host:
    replica_id: 2
    raft_address: "mb2:21512"
    wal_dir: "/data"
    nodehost_dir: "/data"
    deployment_id: 0
    peer: 
        1: "mb1:21511"
        2: "mb2:21512"
        3: "mb3:21513"
replica:
    1:
        bootstrap: false
        id: "topic-a"
        alias: "Topic A"
        type: "message-broker"
        config: |
            {
                "exit_message": "server 2? is closed, bye byee 🧧 💵"
            }
    2:
        bootstrap: false
        id: "ondisk-fsm-poc"
        alias: "Happy"
        type: "happy"
        config: |
            {
                "exit_message": "server 2? is closed, bye byee 🧧 💵",
                "clickhouse_addr": "clickhouse-mb2:9000"
            }
