host:
    replica_id: 3
    raft_address: "mb3:21513"
    wal_dir: "/data"
    nodehost_dir: "/data"
    deployment_id: 0
    peer: 
        1: "mb1:21511"
        2: "mb2:21512"
        3: "mb2:21513"
replica:
    1:
        bootstrap: false
        id: "topic-a"
        alias: "Topic A"
        type: "message-broker"
        config: |
            {
                "exit_message": "server 3, is closed. 🔋"
            }
