// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.1
// source: service/auth-api/auth.proto

package authapi

import (
	session "github.com/desain-gratis/common/types/protobuf/session"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAuthorizationTokenResponse_Error_ErrorCode int32

const (
	GetAuthorizationTokenResponse_Error_ERROR_SERVER_ERROR  GetAuthorizationTokenResponse_Error_ErrorCode = 0
	GetAuthorizationTokenResponse_Error_ERROR_ROLE_REJECTED GetAuthorizationTokenResponse_Error_ErrorCode = 1
)

// Enum value maps for GetAuthorizationTokenResponse_Error_ErrorCode.
var (
	GetAuthorizationTokenResponse_Error_ErrorCode_name = map[int32]string{
		0: "ERROR_SERVER_ERROR",
		1: "ERROR_ROLE_REJECTED",
	}
	GetAuthorizationTokenResponse_Error_ErrorCode_value = map[string]int32{
		"ERROR_SERVER_ERROR":  0,
		"ERROR_ROLE_REJECTED": 1,
	}
)

func (x GetAuthorizationTokenResponse_Error_ErrorCode) Enum() *GetAuthorizationTokenResponse_Error_ErrorCode {
	p := new(GetAuthorizationTokenResponse_Error_ErrorCode)
	*p = x
	return p
}

func (x GetAuthorizationTokenResponse_Error_ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetAuthorizationTokenResponse_Error_ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_service_auth_api_auth_proto_enumTypes[0].Descriptor()
}

func (GetAuthorizationTokenResponse_Error_ErrorCode) Type() protoreflect.EnumType {
	return &file_service_auth_api_auth_proto_enumTypes[0]
}

func (x GetAuthorizationTokenResponse_Error_ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetAuthorizationTokenResponse_Error_ErrorCode.Descriptor instead.
func (GetAuthorizationTokenResponse_Error_ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_service_auth_api_auth_proto_rawDescGZIP(), []int{1, 1, 0}
}

type CreateLoginResponse_Error_ErrorCode int32

const (
	CreateLoginResponse_Error_ERROR_INVALID_CREDENTIAL CreateLoginResponse_Error_ErrorCode = 0
	CreateLoginResponse_Error_ERROR_WEAK_PASSWORD      CreateLoginResponse_Error_ErrorCode = 1
	CreateLoginResponse_Error_ERROR_SERVER_ERROR       CreateLoginResponse_Error_ErrorCode = 2
)

// Enum value maps for CreateLoginResponse_Error_ErrorCode.
var (
	CreateLoginResponse_Error_ErrorCode_name = map[int32]string{
		0: "ERROR_INVALID_CREDENTIAL",
		1: "ERROR_WEAK_PASSWORD",
		2: "ERROR_SERVER_ERROR",
	}
	CreateLoginResponse_Error_ErrorCode_value = map[string]int32{
		"ERROR_INVALID_CREDENTIAL": 0,
		"ERROR_WEAK_PASSWORD":      1,
		"ERROR_SERVER_ERROR":       2,
	}
)

func (x CreateLoginResponse_Error_ErrorCode) Enum() *CreateLoginResponse_Error_ErrorCode {
	p := new(CreateLoginResponse_Error_ErrorCode)
	*p = x
	return p
}

func (x CreateLoginResponse_Error_ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateLoginResponse_Error_ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_service_auth_api_auth_proto_enumTypes[1].Descriptor()
}

func (CreateLoginResponse_Error_ErrorCode) Type() protoreflect.EnumType {
	return &file_service_auth_api_auth_proto_enumTypes[1]
}

func (x CreateLoginResponse_Error_ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateLoginResponse_Error_ErrorCode.Descriptor instead.
func (CreateLoginResponse_Error_ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_service_auth_api_auth_proto_rawDescGZIP(), []int{3, 1, 0}
}

type LoginResponse_Error_ErrorCode int32

const (
	LoginResponse_Error_ERROR_UNSUPPORTED_LOGIN_TYPE LoginResponse_Error_ErrorCode = 0
	LoginResponse_Error_ERROR_INVALID_TOKEN          LoginResponse_Error_ErrorCode = 1
	LoginResponse_Error_ERROR_SERVER_ERROR           LoginResponse_Error_ErrorCode = 2
	LoginResponse_Error_ERROR_INVALID_CREDENTIAL     LoginResponse_Error_ErrorCode = 3
)

// Enum value maps for LoginResponse_Error_ErrorCode.
var (
	LoginResponse_Error_ErrorCode_name = map[int32]string{
		0: "ERROR_UNSUPPORTED_LOGIN_TYPE",
		1: "ERROR_INVALID_TOKEN",
		2: "ERROR_SERVER_ERROR",
		3: "ERROR_INVALID_CREDENTIAL",
	}
	LoginResponse_Error_ErrorCode_value = map[string]int32{
		"ERROR_UNSUPPORTED_LOGIN_TYPE": 0,
		"ERROR_INVALID_TOKEN":          1,
		"ERROR_SERVER_ERROR":           2,
		"ERROR_INVALID_CREDENTIAL":     3,
	}
)

func (x LoginResponse_Error_ErrorCode) Enum() *LoginResponse_Error_ErrorCode {
	p := new(LoginResponse_Error_ErrorCode)
	*p = x
	return p
}

func (x LoginResponse_Error_ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginResponse_Error_ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_service_auth_api_auth_proto_enumTypes[2].Descriptor()
}

func (LoginResponse_Error_ErrorCode) Type() protoreflect.EnumType {
	return &file_service_auth_api_auth_proto_enumTypes[2]
}

func (x LoginResponse_Error_ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginResponse_Error_ErrorCode.Descriptor instead.
func (LoginResponse_Error_ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_service_auth_api_auth_proto_rawDescGZIP(), []int{5, 1, 0}
}

type LogoutResponse_Error_ErrorCode int32

const (
	LogoutResponse_Error_ERROR_SERVER_ERROR        LogoutResponse_Error_ErrorCode = 0
	LogoutResponse_Error_ERROR_AUTHORIZATION_ERROR LogoutResponse_Error_ErrorCode = 1
)

// Enum value maps for LogoutResponse_Error_ErrorCode.
var (
	LogoutResponse_Error_ErrorCode_name = map[int32]string{
		0: "ERROR_SERVER_ERROR",
		1: "ERROR_AUTHORIZATION_ERROR",
	}
	LogoutResponse_Error_ErrorCode_value = map[string]int32{
		"ERROR_SERVER_ERROR":        0,
		"ERROR_AUTHORIZATION_ERROR": 1,
	}
)

func (x LogoutResponse_Error_ErrorCode) Enum() *LogoutResponse_Error_ErrorCode {
	p := new(LogoutResponse_Error_ErrorCode)
	*p = x
	return p
}

func (x LogoutResponse_Error_ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogoutResponse_Error_ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_service_auth_api_auth_proto_enumTypes[3].Descriptor()
}

func (LogoutResponse_Error_ErrorCode) Type() protoreflect.EnumType {
	return &file_service_auth_api_auth_proto_enumTypes[3]
}

func (x LogoutResponse_Error_ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogoutResponse_Error_ErrorCode.Descriptor instead.
func (LogoutResponse_Error_ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_service_auth_api_auth_proto_rawDescGZIP(), []int{7, 1, 0}
}

type SigningKeyResponse_Error_ErrorCode int32

const (
	SigningKeyResponse_Error_ERROR_SERVER_ERROR SigningKeyResponse_Error_ErrorCode = 0
)

// Enum value maps for SigningKeyResponse_Error_ErrorCode.
var (
	SigningKeyResponse_Error_ErrorCode_name = map[int32]string{
		0: "ERROR_SERVER_ERROR",
	}
	SigningKeyResponse_Error_ErrorCode_value = map[string]int32{
		"ERROR_SERVER_ERROR": 0,
	}
)

func (x SigningKeyResponse_Error_ErrorCode) Enum() *SigningKeyResponse_Error_ErrorCode {
	p := new(SigningKeyResponse_Error_ErrorCode)
	*p = x
	return p
}

func (x SigningKeyResponse_Error_ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SigningKeyResponse_Error_ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_service_auth_api_auth_proto_enumTypes[4].Descriptor()
}

func (SigningKeyResponse_Error_ErrorCode) Type() protoreflect.EnumType {
	return &file_service_auth_api_auth_proto_enumTypes[4]
}

func (x SigningKeyResponse_Error_ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SigningKeyResponse_Error_ErrorCode.Descriptor instead.
func (SigningKeyResponse_Error_ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_service_auth_api_auth_proto_rawDescGZIP(), []int{9, 1, 0}
}

type TrackLoginResponse_Error_ErrorCode int32

const (
	TrackLoginResponse_Error_ERROR_SERVER_ERROR TrackLoginResponse_Error_ErrorCode = 0
)

// Enum value maps for TrackLoginResponse_Error_ErrorCode.
var (
	TrackLoginResponse_Error_ErrorCode_name = map[int32]string{
		0: "ERROR_SERVER_ERROR",
	}
	TrackLoginResponse_Error_ErrorCode_value = map[string]int32{
		"ERROR_SERVER_ERROR": 0,
	}
)

func (x TrackLoginResponse_Error_ErrorCode) Enum() *TrackLoginResponse_Error_ErrorCode {
	p := new(TrackLoginResponse_Error_ErrorCode)
	*p = x
	return p
}

func (x TrackLoginResponse_Error_ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrackLoginResponse_Error_ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_service_auth_api_auth_proto_enumTypes[5].Descriptor()
}

func (TrackLoginResponse_Error_ErrorCode) Type() protoreflect.EnumType {
	return &file_service_auth_api_auth_proto_enumTypes[5]
}

func (x TrackLoginResponse_Error_ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrackLoginResponse_Error_ErrorCode.Descriptor instead.
func (TrackLoginResponse_Error_ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_service_auth_api_auth_proto_rawDescGZIP(), []int{11, 1, 0}
}

type GetAuthorizationTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Session *session.Session `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Roles   []string         `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
}

func (x *GetAuthorizationTokenRequest) Reset() {
	*x = GetAuthorizationTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_auth_api_auth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAuthorizationTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorizationTokenRequest) ProtoMessage() {}

func (x *GetAuthorizationTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_auth_api_auth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorizationTokenRequest.ProtoReflect.Descriptor instead.
func (*GetAuthorizationTokenRequest) Descriptor() ([]byte, []int) {
	return file_service_auth_api_auth_proto_rawDescGZIP(), []int{0}
}

func (x *GetAuthorizationTokenRequest) GetSession() *session.Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *GetAuthorizationTokenRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type GetAuthorizationTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success *GetAuthorizationTokenResponse_Success `protobuf:"bytes,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   *GetAuthorizationTokenResponse_Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetAuthorizationTokenResponse) Reset() {
	*x = GetAuthorizationTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_auth_api_auth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAuthorizationTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorizationTokenResponse) ProtoMessage() {}

func (x *GetAuthorizationTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_auth_api_auth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorizationTokenResponse.ProtoReflect.Descriptor instead.
func (*GetAuthorizationTokenResponse) Descriptor() ([]byte, []int) {
	return file_service_auth_api_auth_proto_rawDescGZIP(), []int{1}
}

func (x *GetAuthorizationTokenResponse) GetSuccess() *GetAuthorizationTokenResponse_Success {
	if x != nil {
		return x.Success
	}
	return nil
}

func (x *GetAuthorizationTokenResponse) GetError() *GetAuthorizationTokenResponse_Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type CreateLoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Credential *session.Credential `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
}

func (x *CreateLoginRequest) Reset() {
	*x = CreateLoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_auth_api_auth_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLoginRequest) ProtoMessage() {}

func (x *CreateLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_auth_api_auth_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLoginRequest.ProtoReflect.Descriptor instead.
func (*CreateLoginRequest) Descriptor() ([]byte, []int) {
	return file_service_auth_api_auth_proto_rawDescGZIP(), []int{2}
}

func (x *CreateLoginRequest) GetCredential() *session.Credential {
	if x != nil {
		return x.Credential
	}
	return nil
}

type CreateLoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success *CreateLoginResponse_Success `protobuf:"bytes,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   *CreateLoginResponse_Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *CreateLoginResponse) Reset() {
	*x = CreateLoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_auth_api_auth_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLoginResponse) ProtoMessage() {}

func (x *CreateLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_auth_api_auth_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLoginResponse.ProtoReflect.Descriptor instead.
func (*CreateLoginResponse) Descriptor() ([]byte, []int) {
	return file_service_auth_api_auth_proto_rawDescGZIP(), []int{3}
}

func (x *CreateLoginResponse) GetSuccess() *CreateLoginResponse_Success {
	if x != nil {
		return x.Success
	}
	return nil
}

func (x *CreateLoginResponse) GetError() *CreateLoginResponse_Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Login data is the OIDC auth token from provider such as Google or facebook
//
// Google: https://developers.google.com/identity/sign-in/android/backend-auth
// Facebook: https://developers.facebook.com/docs/facebook-login/android
type LoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdToken  string `protobuf:"bytes,1,opt,name=id_token,json=idToken,proto3" json:"id_token,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_auth_api_auth_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_auth_api_auth_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_service_auth_api_auth_proto_rawDescGZIP(), []int{4}
}

func (x *LoginRequest) GetIdToken() string {
	if x != nil {
		return x.IdToken
	}
	return ""
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success *LoginResponse_Success `protobuf:"bytes,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   *LoginResponse_Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_auth_api_auth_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_auth_api_auth_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_service_auth_api_auth_proto_rawDescGZIP(), []int{5}
}

func (x *LoginResponse) GetSuccess() *LoginResponse_Success {
	if x != nil {
		return x.Success
	}
	return nil
}

func (x *LoginResponse) GetError() *LoginResponse_Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type LogoutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Session *session.Session `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	// optional user ID if want to force other user
	UserID *session.OIDCClaim `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_auth_api_auth_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_auth_api_auth_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_service_auth_api_auth_proto_rawDescGZIP(), []int{6}
}

func (x *LogoutRequest) GetSession() *session.Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *LogoutRequest) GetUserID() *session.OIDCClaim {
	if x != nil {
		return x.UserID
	}
	return nil
}

type LogoutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success *LogoutResponse_Success `protobuf:"bytes,1,opt,name=success,proto3,oneof" json:"success,omitempty"`
	Error   *LogoutResponse_Error   `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_auth_api_auth_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_auth_api_auth_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_service_auth_api_auth_proto_rawDescGZIP(), []int{7}
}

func (x *LogoutResponse) GetSuccess() *LogoutResponse_Success {
	if x != nil {
		return x.Success
	}
	return nil
}

func (x *LogoutResponse) GetError() *LogoutResponse_Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type SigningKeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyId string `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
}

func (x *SigningKeyRequest) Reset() {
	*x = SigningKeyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_auth_api_auth_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SigningKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningKeyRequest) ProtoMessage() {}

func (x *SigningKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_auth_api_auth_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningKeyRequest.ProtoReflect.Descriptor instead.
func (*SigningKeyRequest) Descriptor() ([]byte, []int) {
	return file_service_auth_api_auth_proto_rawDescGZIP(), []int{8}
}

func (x *SigningKeyRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

type SigningKeyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success *SigningKeyResponse_Success `protobuf:"bytes,1,opt,name=success,proto3,oneof" json:"success,omitempty"`
	Error   *SigningKeyResponse_Error   `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
}

func (x *SigningKeyResponse) Reset() {
	*x = SigningKeyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_auth_api_auth_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SigningKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningKeyResponse) ProtoMessage() {}

func (x *SigningKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_auth_api_auth_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningKeyResponse.ProtoReflect.Descriptor instead.
func (*SigningKeyResponse) Descriptor() ([]byte, []int) {
	return file_service_auth_api_auth_proto_rawDescGZIP(), []int{9}
}

func (x *SigningKeyResponse) GetSuccess() *SigningKeyResponse_Success {
	if x != nil {
		return x.Success
	}
	return nil
}

func (x *SigningKeyResponse) GetError() *SigningKeyResponse_Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// TrackLoginRequest for tracking and verifying user data
type TrackLoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *TrackingData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *TrackLoginRequest) Reset() {
	*x = TrackLoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_auth_api_auth_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackLoginRequest) ProtoMessage() {}

func (x *TrackLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_auth_api_auth_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackLoginRequest.ProtoReflect.Descriptor instead.
func (*TrackLoginRequest) Descriptor() ([]byte, []int) {
	return file_service_auth_api_auth_proto_rawDescGZIP(), []int{10}
}

func (x *TrackLoginRequest) GetData() *TrackingData {
	if x != nil {
		return x.Data
	}
	return nil
}

// TrackLoginResponse for acknowledgement of the tracking data
type TrackLoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success *TrackLoginResponse_Success `protobuf:"bytes,1,opt,name=success,proto3,oneof" json:"success,omitempty"`
	Error   *TrackLoginResponse_Error   `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
}

func (x *TrackLoginResponse) Reset() {
	*x = TrackLoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_auth_api_auth_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackLoginResponse) ProtoMessage() {}

func (x *TrackLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_auth_api_auth_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackLoginResponse.ProtoReflect.Descriptor instead.
func (*TrackLoginResponse) Descriptor() ([]byte, []int) {
	return file_service_auth_api_auth_proto_rawDescGZIP(), []int{11}
}

func (x *TrackLoginResponse) GetSuccess() *TrackLoginResponse_Success {
	if x != nil {
		return x.Success
	}
	return nil
}

func (x *TrackLoginResponse) GetError() *TrackLoginResponse_Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Login related data
type TrackingData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Location *Geolocation `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Device   string       `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	//	oneof device_info {
	//	    android.Data android = 3;
	//	}
	Nonce      int64                  `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ClientTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=client_time,json=clientTime,proto3" json:"client_time,omitempty"` // should be with time zone
}

func (x *TrackingData) Reset() {
	*x = TrackingData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_auth_api_auth_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackingData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackingData) ProtoMessage() {}

func (x *TrackingData) ProtoReflect() protoreflect.Message {
	mi := &file_service_auth_api_auth_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackingData.ProtoReflect.Descriptor instead.
func (*TrackingData) Descriptor() ([]byte, []int) {
	return file_service_auth_api_auth_proto_rawDescGZIP(), []int{12}
}

func (x *TrackingData) GetLocation() *Geolocation {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *TrackingData) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *TrackingData) GetNonce() int64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *TrackingData) GetClientTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ClientTime
	}
	return nil
}

// Geolocation contains WGS84 lat lon information
type Geolocation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lat float64 `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon float64 `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
}

func (x *Geolocation) Reset() {
	*x = Geolocation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_auth_api_auth_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Geolocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Geolocation) ProtoMessage() {}

func (x *Geolocation) ProtoReflect() protoreflect.Message {
	mi := &file_service_auth_api_auth_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Geolocation.ProtoReflect.Descriptor instead.
func (*Geolocation) Descriptor() ([]byte, []int) {
	return file_service_auth_api_auth_proto_rawDescGZIP(), []int{13}
}

func (x *Geolocation) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Geolocation) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

type GetAuthorizationTokenResponse_Success struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string            `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Token   map[string]string `protobuf:"bytes,2,rep,name=token,proto3" json:"token,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *GetAuthorizationTokenResponse_Success) Reset() {
	*x = GetAuthorizationTokenResponse_Success{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_auth_api_auth_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAuthorizationTokenResponse_Success) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorizationTokenResponse_Success) ProtoMessage() {}

func (x *GetAuthorizationTokenResponse_Success) ProtoReflect() protoreflect.Message {
	mi := &file_service_auth_api_auth_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorizationTokenResponse_Success.ProtoReflect.Descriptor instead.
func (*GetAuthorizationTokenResponse_Success) Descriptor() ([]byte, []int) {
	return file_service_auth_api_auth_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetAuthorizationTokenResponse_Success) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetAuthorizationTokenResponse_Success) GetToken() map[string]string {
	if x != nil {
		return x.Token
	}
	return nil
}

type GetAuthorizationTokenResponse_Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    GetAuthorizationTokenResponse_Error_ErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=authapi.GetAuthorizationTokenResponse_Error_ErrorCode" json:"code,omitempty"`
	Message string                                        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GetAuthorizationTokenResponse_Error) Reset() {
	*x = GetAuthorizationTokenResponse_Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_auth_api_auth_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAuthorizationTokenResponse_Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorizationTokenResponse_Error) ProtoMessage() {}

func (x *GetAuthorizationTokenResponse_Error) ProtoReflect() protoreflect.Message {
	mi := &file_service_auth_api_auth_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorizationTokenResponse_Error.ProtoReflect.Descriptor instead.
func (*GetAuthorizationTokenResponse_Error) Descriptor() ([]byte, []int) {
	return file_service_auth_api_auth_proto_rawDescGZIP(), []int{1, 1}
}

func (x *GetAuthorizationTokenResponse_Error) GetCode() GetAuthorizationTokenResponse_Error_ErrorCode {
	if x != nil {
		return x.Code
	}
	return GetAuthorizationTokenResponse_Error_ERROR_SERVER_ERROR
}

func (x *GetAuthorizationTokenResponse_Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateLoginResponse_Success struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CreateLoginResponse_Success) Reset() {
	*x = CreateLoginResponse_Success{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_auth_api_auth_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLoginResponse_Success) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLoginResponse_Success) ProtoMessage() {}

func (x *CreateLoginResponse_Success) ProtoReflect() protoreflect.Message {
	mi := &file_service_auth_api_auth_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLoginResponse_Success.ProtoReflect.Descriptor instead.
func (*CreateLoginResponse_Success) Descriptor() ([]byte, []int) {
	return file_service_auth_api_auth_proto_rawDescGZIP(), []int{3, 0}
}

func (x *CreateLoginResponse_Success) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateLoginResponse_Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    CreateLoginResponse_Error_ErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=authapi.CreateLoginResponse_Error_ErrorCode" json:"code,omitempty"`
	Message string                              `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CreateLoginResponse_Error) Reset() {
	*x = CreateLoginResponse_Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_auth_api_auth_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLoginResponse_Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLoginResponse_Error) ProtoMessage() {}

func (x *CreateLoginResponse_Error) ProtoReflect() protoreflect.Message {
	mi := &file_service_auth_api_auth_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLoginResponse_Error.ProtoReflect.Descriptor instead.
func (*CreateLoginResponse_Error) Descriptor() ([]byte, []int) {
	return file_service_auth_api_auth_proto_rawDescGZIP(), []int{3, 1}
}

func (x *CreateLoginResponse_Error) GetCode() CreateLoginResponse_Error_ErrorCode {
	if x != nil {
		return x.Code
	}
	return CreateLoginResponse_Error_ERROR_INVALID_CREDENTIAL
}

func (x *CreateLoginResponse_Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LoginResponse_Success struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Session *session.Session `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
}

func (x *LoginResponse_Success) Reset() {
	*x = LoginResponse_Success{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_auth_api_auth_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResponse_Success) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse_Success) ProtoMessage() {}

func (x *LoginResponse_Success) ProtoReflect() protoreflect.Message {
	mi := &file_service_auth_api_auth_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse_Success.ProtoReflect.Descriptor instead.
func (*LoginResponse_Success) Descriptor() ([]byte, []int) {
	return file_service_auth_api_auth_proto_rawDescGZIP(), []int{5, 0}
}

func (x *LoginResponse_Success) GetSession() *session.Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type LoginResponse_Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    LoginResponse_Error_ErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=authapi.LoginResponse_Error_ErrorCode" json:"code,omitempty"`
	Message string                        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *LoginResponse_Error) Reset() {
	*x = LoginResponse_Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_auth_api_auth_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResponse_Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse_Error) ProtoMessage() {}

func (x *LoginResponse_Error) ProtoReflect() protoreflect.Message {
	mi := &file_service_auth_api_auth_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse_Error.ProtoReflect.Descriptor instead.
func (*LoginResponse_Error) Descriptor() ([]byte, []int) {
	return file_service_auth_api_auth_proto_rawDescGZIP(), []int{5, 1}
}

func (x *LoginResponse_Error) GetCode() LoginResponse_Error_ErrorCode {
	if x != nil {
		return x.Code
	}
	return LoginResponse_Error_ERROR_UNSUPPORTED_LOGIN_TYPE
}

func (x *LoginResponse_Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LogoutResponse_Success struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LogoutResponse_Success) Reset() {
	*x = LogoutResponse_Success{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_auth_api_auth_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogoutResponse_Success) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse_Success) ProtoMessage() {}

func (x *LogoutResponse_Success) ProtoReflect() protoreflect.Message {
	mi := &file_service_auth_api_auth_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse_Success.ProtoReflect.Descriptor instead.
func (*LogoutResponse_Success) Descriptor() ([]byte, []int) {
	return file_service_auth_api_auth_proto_rawDescGZIP(), []int{7, 0}
}

type LogoutResponse_Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    LogoutResponse_Error_ErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=authapi.LogoutResponse_Error_ErrorCode" json:"code,omitempty"`
	Message string                         `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *LogoutResponse_Error) Reset() {
	*x = LogoutResponse_Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_auth_api_auth_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogoutResponse_Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse_Error) ProtoMessage() {}

func (x *LogoutResponse_Error) ProtoReflect() protoreflect.Message {
	mi := &file_service_auth_api_auth_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse_Error.ProtoReflect.Descriptor instead.
func (*LogoutResponse_Error) Descriptor() ([]byte, []int) {
	return file_service_auth_api_auth_proto_rawDescGZIP(), []int{7, 1}
}

func (x *LogoutResponse_Error) GetCode() LogoutResponse_Error_ErrorCode {
	if x != nil {
		return x.Code
	}
	return LogoutResponse_Error_ERROR_SERVER_ERROR
}

func (x *LogoutResponse_Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SigningKeyResponse_Success struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyId  string `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	KeyPem string `protobuf:"bytes,2,opt,name=key_pem,json=keyPem,proto3" json:"key_pem,omitempty"`
}

func (x *SigningKeyResponse_Success) Reset() {
	*x = SigningKeyResponse_Success{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_auth_api_auth_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SigningKeyResponse_Success) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningKeyResponse_Success) ProtoMessage() {}

func (x *SigningKeyResponse_Success) ProtoReflect() protoreflect.Message {
	mi := &file_service_auth_api_auth_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningKeyResponse_Success.ProtoReflect.Descriptor instead.
func (*SigningKeyResponse_Success) Descriptor() ([]byte, []int) {
	return file_service_auth_api_auth_proto_rawDescGZIP(), []int{9, 0}
}

func (x *SigningKeyResponse_Success) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *SigningKeyResponse_Success) GetKeyPem() string {
	if x != nil {
		return x.KeyPem
	}
	return ""
}

type SigningKeyResponse_Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    SigningKeyResponse_Error_ErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=authapi.SigningKeyResponse_Error_ErrorCode" json:"code,omitempty"`
	Message string                             `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SigningKeyResponse_Error) Reset() {
	*x = SigningKeyResponse_Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_auth_api_auth_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SigningKeyResponse_Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningKeyResponse_Error) ProtoMessage() {}

func (x *SigningKeyResponse_Error) ProtoReflect() protoreflect.Message {
	mi := &file_service_auth_api_auth_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningKeyResponse_Error.ProtoReflect.Descriptor instead.
func (*SigningKeyResponse_Error) Descriptor() ([]byte, []int) {
	return file_service_auth_api_auth_proto_rawDescGZIP(), []int{9, 1}
}

func (x *SigningKeyResponse_Error) GetCode() SigningKeyResponse_Error_ErrorCode {
	if x != nil {
		return x.Code
	}
	return SigningKeyResponse_Error_ERROR_SERVER_ERROR
}

func (x *SigningKeyResponse_Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TrackLoginResponse_Success struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TrackLoginResponse_Success) Reset() {
	*x = TrackLoginResponse_Success{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_auth_api_auth_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackLoginResponse_Success) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackLoginResponse_Success) ProtoMessage() {}

func (x *TrackLoginResponse_Success) ProtoReflect() protoreflect.Message {
	mi := &file_service_auth_api_auth_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackLoginResponse_Success.ProtoReflect.Descriptor instead.
func (*TrackLoginResponse_Success) Descriptor() ([]byte, []int) {
	return file_service_auth_api_auth_proto_rawDescGZIP(), []int{11, 0}
}

type TrackLoginResponse_Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    TrackLoginResponse_Error_ErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=authapi.TrackLoginResponse_Error_ErrorCode" json:"code,omitempty"`
	Message string                             `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *TrackLoginResponse_Error) Reset() {
	*x = TrackLoginResponse_Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_auth_api_auth_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackLoginResponse_Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackLoginResponse_Error) ProtoMessage() {}

func (x *TrackLoginResponse_Error) ProtoReflect() protoreflect.Message {
	mi := &file_service_auth_api_auth_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackLoginResponse_Error.ProtoReflect.Descriptor instead.
func (*TrackLoginResponse_Error) Descriptor() ([]byte, []int) {
	return file_service_auth_api_auth_proto_rawDescGZIP(), []int{11, 1}
}

func (x *TrackLoginResponse_Error) GetCode() TrackLoginResponse_Error_ErrorCode {
	if x != nil {
		return x.Code
	}
	return TrackLoginResponse_Error_ERROR_SERVER_ERROR
}

func (x *TrackLoginResponse_Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_service_auth_api_auth_proto protoreflect.FileDescriptor

var file_service_auth_api_auth_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2d, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x61,
	0x75, 0x74, 0x68, 0x61, 0x70, 0x69, 0x1a, 0x14, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2f,
	0x63, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x60, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x41, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x22, 0x8c, 0x04, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x41, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x61, 0x75, 0x74, 0x68,
	0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x12, 0x42, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x2c, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x41,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x1a, 0xae, 0x01, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x4f, 0x0a, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x39, 0x2e, 0x61, 0x75,
	0x74, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69,
	0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x2e, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x1a, 0x38, 0x0a,
	0x0a, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0xab, 0x01, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x4a, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x36, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x3c, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x12, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x53, 0x45,
	0x52, 0x56, 0x45, 0x52, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13,
	0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x52, 0x4f, 0x4c, 0x45, 0x5f, 0x52, 0x45, 0x4a, 0x45, 0x43,
	0x54, 0x45, 0x44, 0x10, 0x01, 0x22, 0x49, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x0a, 0x63,
	0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x61, 0x6c, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c,
	0x22, 0xf6, 0x02, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x61, 0x75, 0x74, 0x68,
	0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x38, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x61, 0x70,
	0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x1a, 0x23, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0xbf, 0x01, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x40, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x2c, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x5a, 0x0a,
	0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x18, 0x45, 0x52,
	0x52, 0x4f, 0x52, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x43, 0x52, 0x45, 0x44,
	0x45, 0x4e, 0x54, 0x49, 0x41, 0x4c, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x5f, 0x57, 0x45, 0x41, 0x4b, 0x5f, 0x50, 0x41, 0x53, 0x53, 0x57, 0x4f, 0x52, 0x44, 0x10,
	0x01, 0x12, 0x16, 0x0a, 0x12, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x45,
	0x52, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x02, 0x22, 0x61, 0x0a, 0x0c, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x64, 0x5f,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x64, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x92, 0x03, 0x0a,
	0x0d, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x32, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x61, 0x70,
	0x69, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x1a, 0x35, 0x0a, 0x07,
	0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x2a, 0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x1a, 0xdb, 0x01, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x3a, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x26, 0x2e, 0x61, 0x75,
	0x74, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x7c, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x20, 0x0a, 0x1c, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x55, 0x4e, 0x53, 0x55, 0x50, 0x50,
	0x4f, 0x52, 0x54, 0x45, 0x44, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x49, 0x4e, 0x56, 0x41,
	0x4c, 0x49, 0x44, 0x5f, 0x54, 0x4f, 0x4b, 0x45, 0x4e, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x45,
	0x52, 0x52, 0x4f, 0x52, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x5f, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x10, 0x02, 0x12, 0x1c, 0x0a, 0x18, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x49, 0x4e, 0x56,
	0x41, 0x4c, 0x49, 0x44, 0x5f, 0x43, 0x52, 0x45, 0x44, 0x45, 0x4e, 0x54, 0x49, 0x41, 0x4c, 0x10,
	0x03, 0x22, 0x67, 0x0a, 0x0d, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2a, 0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2a,
	0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x4f, 0x49, 0x44, 0x43, 0x43, 0x6c, 0x61,
	0x69, 0x6d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0xd0, 0x02, 0x0a, 0x0e, 0x4c,
	0x6f, 0x67, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x61, 0x75, 0x74, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x48,
	0x00, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x88, 0x01, 0x01, 0x12, 0x38, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x61,
	0x75, 0x74, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x01, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x1a, 0x09, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x1a, 0xa2, 0x01, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x3b, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e, 0x61, 0x75, 0x74,
	0x68, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x42, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x16, 0x0a, 0x12, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52,
	0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00, 0x12, 0x1d, 0x0a, 0x19, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x5f, 0x41, 0x55, 0x54, 0x48, 0x4f, 0x52, 0x49, 0x5a, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f,
	0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x2a, 0x0a,
	0x11, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x6b, 0x65, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x6b, 0x65, 0x79, 0x49, 0x64, 0x22, 0xf1, 0x02, 0x0a, 0x12, 0x53, 0x69,
	0x67, 0x6e, 0x69, 0x6e, 0x67, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x42, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x23, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x69, 0x67, 0x6e,
	0x69, 0x6e, 0x67, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x48, 0x00, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x88, 0x01, 0x01, 0x12, 0x3c, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x69,
	0x67, 0x6e, 0x69, 0x6e, 0x67, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x01, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x88,
	0x01, 0x01, 0x1a, 0x39, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x15, 0x0a,
	0x06, 0x6b, 0x65, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6b,
	0x65, 0x79, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x5f, 0x70, 0x65, 0x6d, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6b, 0x65, 0x79, 0x50, 0x65, 0x6d, 0x1a, 0x87, 0x01,
	0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x3f, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2b, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x61, 0x70, 0x69, 0x2e,
	0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x23, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x16, 0x0a, 0x12, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x5f,
	0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x3e, 0x0a,
	0x11, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x29, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b,
	0x69, 0x6e, 0x67, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xc1, 0x02,
	0x0a, 0x12, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x61, 0x70, 0x69, 0x2e,
	0x54, 0x72, 0x61, 0x63, 0x6b, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x48, 0x00, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x88, 0x01, 0x01, 0x12, 0x3c, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x61, 0x70,
	0x69, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x01, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x1a, 0x09, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x1a, 0x87, 0x01, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x3f, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2b, 0x2e, 0x61, 0x75, 0x74, 0x68,
	0x61, 0x70, 0x69, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x23, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x12, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x53, 0x45, 0x52,
	0x56, 0x45, 0x52, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00, 0x42, 0x0a, 0x0a, 0x08, 0x5f,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x22, 0xab, 0x01, 0x0a, 0x0c, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x30, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x47,
	0x65, 0x6f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6e, 0x6f, 0x6e,
	0x63, 0x65, 0x12, 0x3b, 0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x22,
	0x31, 0x0a, 0x0b, 0x47, 0x65, 0x6f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10,
	0x0a, 0x03, 0x6c, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x61, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c,
	0x6f, 0x6e, 0x32, 0x97, 0x04, 0x0a, 0x15, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3c, 0x0a, 0x0b,
	0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x15, 0x2e, 0x61, 0x75,
	0x74, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x16, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x11, 0x55, 0x73,
	0x65, 0x72, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12,
	0x15, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x61, 0x70, 0x69,
	0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39,
	0x0a, 0x06, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x12, 0x16, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x61,
	0x70, 0x69, 0x2e, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x17, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x6f, 0x67, 0x6f, 0x75,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x0d, 0x47, 0x65, 0x74,
	0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67, 0x4b, 0x65, 0x79, 0x12, 0x1a, 0x2e, 0x61, 0x75, 0x74,
	0x68, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67, 0x4b, 0x65, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x61, 0x70, 0x69,
	0x2e, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x12, 0x1b, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1c, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x66, 0x0a,
	0x15, 0x47, 0x65, 0x74, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x25, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x61, 0x70, 0x69,
	0x2e, 0x47, 0x65, 0x74, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e,
	0x61, 0x75, 0x74, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x0a, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x12, 0x1a, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x72,
	0x61, 0x63, 0x6b, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1b, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x48, 0x5a, 0x46,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x65, 0x73, 0x61, 0x69,
	0x6e, 0x2d, 0x67, 0x72, 0x61, 0x74, 0x69, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x61, 0x70, 0x69, 0x3b, 0x61,
	0x75, 0x74, 0x68, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_auth_api_auth_proto_rawDescOnce sync.Once
	file_service_auth_api_auth_proto_rawDescData = file_service_auth_api_auth_proto_rawDesc
)

func file_service_auth_api_auth_proto_rawDescGZIP() []byte {
	file_service_auth_api_auth_proto_rawDescOnce.Do(func() {
		file_service_auth_api_auth_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_auth_api_auth_proto_rawDescData)
	})
	return file_service_auth_api_auth_proto_rawDescData
}

var file_service_auth_api_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_service_auth_api_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_service_auth_api_auth_proto_goTypes = []interface{}{
	(GetAuthorizationTokenResponse_Error_ErrorCode)(0), // 0: authapi.GetAuthorizationTokenResponse.Error.ErrorCode
	(CreateLoginResponse_Error_ErrorCode)(0),           // 1: authapi.CreateLoginResponse.Error.ErrorCode
	(LoginResponse_Error_ErrorCode)(0),                 // 2: authapi.LoginResponse.Error.ErrorCode
	(LogoutResponse_Error_ErrorCode)(0),                // 3: authapi.LogoutResponse.Error.ErrorCode
	(SigningKeyResponse_Error_ErrorCode)(0),            // 4: authapi.SigningKeyResponse.Error.ErrorCode
	(TrackLoginResponse_Error_ErrorCode)(0),            // 5: authapi.TrackLoginResponse.Error.ErrorCode
	(*GetAuthorizationTokenRequest)(nil),               // 6: authapi.GetAuthorizationTokenRequest
	(*GetAuthorizationTokenResponse)(nil),              // 7: authapi.GetAuthorizationTokenResponse
	(*CreateLoginRequest)(nil),                         // 8: authapi.CreateLoginRequest
	(*CreateLoginResponse)(nil),                        // 9: authapi.CreateLoginResponse
	(*LoginRequest)(nil),                               // 10: authapi.LoginRequest
	(*LoginResponse)(nil),                              // 11: authapi.LoginResponse
	(*LogoutRequest)(nil),                              // 12: authapi.LogoutRequest
	(*LogoutResponse)(nil),                             // 13: authapi.LogoutResponse
	(*SigningKeyRequest)(nil),                          // 14: authapi.SigningKeyRequest
	(*SigningKeyResponse)(nil),                         // 15: authapi.SigningKeyResponse
	(*TrackLoginRequest)(nil),                          // 16: authapi.TrackLoginRequest
	(*TrackLoginResponse)(nil),                         // 17: authapi.TrackLoginResponse
	(*TrackingData)(nil),                               // 18: authapi.TrackingData
	(*Geolocation)(nil),                                // 19: authapi.Geolocation
	(*GetAuthorizationTokenResponse_Success)(nil),      // 20: authapi.GetAuthorizationTokenResponse.Success
	(*GetAuthorizationTokenResponse_Error)(nil),        // 21: authapi.GetAuthorizationTokenResponse.Error
	nil,                                 // 22: authapi.GetAuthorizationTokenResponse.Success.TokenEntry
	(*CreateLoginResponse_Success)(nil), // 23: authapi.CreateLoginResponse.Success
	(*CreateLoginResponse_Error)(nil),   // 24: authapi.CreateLoginResponse.Error
	(*LoginResponse_Success)(nil),       // 25: authapi.LoginResponse.Success
	(*LoginResponse_Error)(nil),         // 26: authapi.LoginResponse.Error
	(*LogoutResponse_Success)(nil),      // 27: authapi.LogoutResponse.Success
	(*LogoutResponse_Error)(nil),        // 28: authapi.LogoutResponse.Error
	(*SigningKeyResponse_Success)(nil),  // 29: authapi.SigningKeyResponse.Success
	(*SigningKeyResponse_Error)(nil),    // 30: authapi.SigningKeyResponse.Error
	(*TrackLoginResponse_Success)(nil),  // 31: authapi.TrackLoginResponse.Success
	(*TrackLoginResponse_Error)(nil),    // 32: authapi.TrackLoginResponse.Error
	(*session.Session)(nil),             // 33: session.Session
	(*session.Credential)(nil),          // 34: session.Credential
	(*session.OIDCClaim)(nil),           // 35: session.OIDCClaim
	(*timestamppb.Timestamp)(nil),       // 36: google.protobuf.Timestamp
}
var file_service_auth_api_auth_proto_depIdxs = []int32{
	33, // 0: authapi.GetAuthorizationTokenRequest.session:type_name -> session.Session
	20, // 1: authapi.GetAuthorizationTokenResponse.success:type_name -> authapi.GetAuthorizationTokenResponse.Success
	21, // 2: authapi.GetAuthorizationTokenResponse.error:type_name -> authapi.GetAuthorizationTokenResponse.Error
	34, // 3: authapi.CreateLoginRequest.credential:type_name -> session.Credential
	23, // 4: authapi.CreateLoginResponse.success:type_name -> authapi.CreateLoginResponse.Success
	24, // 5: authapi.CreateLoginResponse.error:type_name -> authapi.CreateLoginResponse.Error
	25, // 6: authapi.LoginResponse.success:type_name -> authapi.LoginResponse.Success
	26, // 7: authapi.LoginResponse.error:type_name -> authapi.LoginResponse.Error
	33, // 8: authapi.LogoutRequest.session:type_name -> session.Session
	35, // 9: authapi.LogoutRequest.userID:type_name -> session.OIDCClaim
	27, // 10: authapi.LogoutResponse.success:type_name -> authapi.LogoutResponse.Success
	28, // 11: authapi.LogoutResponse.error:type_name -> authapi.LogoutResponse.Error
	29, // 12: authapi.SigningKeyResponse.success:type_name -> authapi.SigningKeyResponse.Success
	30, // 13: authapi.SigningKeyResponse.error:type_name -> authapi.SigningKeyResponse.Error
	18, // 14: authapi.TrackLoginRequest.data:type_name -> authapi.TrackingData
	31, // 15: authapi.TrackLoginResponse.success:type_name -> authapi.TrackLoginResponse.Success
	32, // 16: authapi.TrackLoginResponse.error:type_name -> authapi.TrackLoginResponse.Error
	19, // 17: authapi.TrackingData.location:type_name -> authapi.Geolocation
	36, // 18: authapi.TrackingData.client_time:type_name -> google.protobuf.Timestamp
	22, // 19: authapi.GetAuthorizationTokenResponse.Success.token:type_name -> authapi.GetAuthorizationTokenResponse.Success.TokenEntry
	0,  // 20: authapi.GetAuthorizationTokenResponse.Error.code:type_name -> authapi.GetAuthorizationTokenResponse.Error.ErrorCode
	1,  // 21: authapi.CreateLoginResponse.Error.code:type_name -> authapi.CreateLoginResponse.Error.ErrorCode
	33, // 22: authapi.LoginResponse.Success.session:type_name -> session.Session
	2,  // 23: authapi.LoginResponse.Error.code:type_name -> authapi.LoginResponse.Error.ErrorCode
	3,  // 24: authapi.LogoutResponse.Error.code:type_name -> authapi.LogoutResponse.Error.ErrorCode
	4,  // 25: authapi.SigningKeyResponse.Error.code:type_name -> authapi.SigningKeyResponse.Error.ErrorCode
	5,  // 26: authapi.TrackLoginResponse.Error.code:type_name -> authapi.TrackLoginResponse.Error.ErrorCode
	10, // 27: authapi.AuthenticationService.GoogleLogin:input_type -> authapi.LoginRequest
	10, // 28: authapi.AuthenticationService.UserPasswordLogin:input_type -> authapi.LoginRequest
	12, // 29: authapi.AuthenticationService.Logout:input_type -> authapi.LogoutRequest
	14, // 30: authapi.AuthenticationService.GetSigningKey:input_type -> authapi.SigningKeyRequest
	8,  // 31: authapi.AuthenticationService.CreateLogin:input_type -> authapi.CreateLoginRequest
	6,  // 32: authapi.AuthenticationService.GetAuthorizationToken:input_type -> authapi.GetAuthorizationTokenRequest
	16, // 33: authapi.AuthenticationService.TrackLogin:input_type -> authapi.TrackLoginRequest
	11, // 34: authapi.AuthenticationService.GoogleLogin:output_type -> authapi.LoginResponse
	11, // 35: authapi.AuthenticationService.UserPasswordLogin:output_type -> authapi.LoginResponse
	13, // 36: authapi.AuthenticationService.Logout:output_type -> authapi.LogoutResponse
	15, // 37: authapi.AuthenticationService.GetSigningKey:output_type -> authapi.SigningKeyResponse
	9,  // 38: authapi.AuthenticationService.CreateLogin:output_type -> authapi.CreateLoginResponse
	7,  // 39: authapi.AuthenticationService.GetAuthorizationToken:output_type -> authapi.GetAuthorizationTokenResponse
	17, // 40: authapi.AuthenticationService.TrackLogin:output_type -> authapi.TrackLoginResponse
	34, // [34:41] is the sub-list for method output_type
	27, // [27:34] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_service_auth_api_auth_proto_init() }
func file_service_auth_api_auth_proto_init() {
	if File_service_auth_api_auth_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_auth_api_auth_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAuthorizationTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_auth_api_auth_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAuthorizationTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_auth_api_auth_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_auth_api_auth_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_auth_api_auth_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_auth_api_auth_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_auth_api_auth_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogoutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_auth_api_auth_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogoutResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_auth_api_auth_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SigningKeyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_auth_api_auth_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SigningKeyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_auth_api_auth_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrackLoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_auth_api_auth_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrackLoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_auth_api_auth_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrackingData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_auth_api_auth_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Geolocation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_auth_api_auth_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAuthorizationTokenResponse_Success); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_auth_api_auth_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAuthorizationTokenResponse_Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_auth_api_auth_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLoginResponse_Success); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_auth_api_auth_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLoginResponse_Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_auth_api_auth_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResponse_Success); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_auth_api_auth_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResponse_Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_auth_api_auth_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogoutResponse_Success); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_auth_api_auth_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogoutResponse_Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_auth_api_auth_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SigningKeyResponse_Success); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_auth_api_auth_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SigningKeyResponse_Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_auth_api_auth_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrackLoginResponse_Success); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_auth_api_auth_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrackLoginResponse_Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_service_auth_api_auth_proto_msgTypes[7].OneofWrappers = []interface{}{}
	file_service_auth_api_auth_proto_msgTypes[9].OneofWrappers = []interface{}{}
	file_service_auth_api_auth_proto_msgTypes[11].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_auth_api_auth_proto_rawDesc,
			NumEnums:      6,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_auth_api_auth_proto_goTypes,
		DependencyIndexes: file_service_auth_api_auth_proto_depIdxs,
		EnumInfos:         file_service_auth_api_auth_proto_enumTypes,
		MessageInfos:      file_service_auth_api_auth_proto_msgTypes,
	}.Build()
	File_service_auth_api_auth_proto = out.File
	file_service_auth_api_auth_proto_rawDesc = nil
	file_service_auth_api_auth_proto_goTypes = nil
	file_service_auth_api_auth_proto_depIdxs = nil
}
